Create 15445.md
CMU-HKN/CMU-ECE-CS-Guide pull request #29
Opened 2021-04-10 01:48 UTC by apoorvtintin

A report on the 15445 Introduction to Database Systems class, this is an elective for ECE major students, this report fulfills a service event for HKN induction requirements.

# Summary of Changes

- Please indicate the classes you are modifying:
  - 18-445

# Checklist:

Make sure that your contributions:

- [Y] Are accurate and will not mislead the reader
- [Y] Do not encourage or cause academic integrity violations
- [Y] Do not offend professors or unfairly criticize the university

2021-04-11 01:04 UTC, mikinty requested changes
Hey thanks! looks good

One thing -- can you add this to the table of contents so there is a link to it in the main README?

2021-04-11 01:04 UTC, mikinty commented on electives/15445.md
> +## What to look out for
should add an extra space here
```suggestion
## What to look out for

```

2021-04-11 15:37 UTC, apoorvtintin commented
> Hey thanks! looks good
> 
> One thing -- can you add this to the table of contents so there is a link to it in the main README?

Thanks for going over it, I added it into README.md

2021-04-16 16:44 UTC, mikinty approved these changes

2021-04-16 16:44 UTC, merged