18-220 changes
CMU-HKN/CMU-ECE-CS-Guide pull request #86
Opened 2023-03-30 03:34 UTC by emilyszabo27

# Summary of Changes

- Please indicate the classes you are modifying:
  - 18-100
  - ...

# Checklist:

- [ ] I have added my entries to the `README.md` table of contents in the root directory as links.

Make sure that your contributions:

- [ ] Are accurate and will not mislead the reader
- [ ] Do not encourage or cause academic integrity violations
- [ ] Do not offend professors or unfairly criticize the university

2023-04-04 21:01 UTC, mikinty requested changes
I think too much is deleted from this note, unless things have changed drastically in the last 2 years

2023-04-04 21:01 UTC, mikinty commented on ece_core/18220.md
> +| HW       | 3          |
I don't know how we want to do this in the future, but I think we should get a distribution of what people think of difficulties...if you have any ideas of how to do that please lmk

I would like to keep HW at 5 if possible, I don't think it's a 3 which signals it's easy. 6 for a lab is much more reasonable I agree.

2023-04-04 21:01 UTC, mikinty commented on ece_core/18220.md
> -When making circuits, people often just string together whatever they can, and just pray it works. What you should do instead, is treat your circuit like code you write in software. Would you write m
I don't think this needs to be deleted

2023-04-04 21:01 UTC, mikinty commented on ece_core/18220.md
> -- You have an oscilloscope, which means you can literally probe in anywhere in your circuit and measure what's going on. This is basically an irl super debugger.
Are these not useful tips?

2023-04-04 21:01 UTC, mikinty commented on ece_core/18220.md
> -- Keep a list of equations/properties as you take the course, as they will help you study for exams in a more condensed way
Are these also not useful?

2023-04-04 21:01 UTC, mikinty commented on ece_core/18220.md
> -- Small signal
Is this not useful?

2023-04-05 17:47 UTC, emilyszabo27 commented
I put in another pull request because I'm not sure how to edit this one. Feel free to dismiss this one and only consider the new pull request, and let me know your thoughts on the new pull request.

2023-04-05 18:27 UTC, merged