Create 18865
CMU-HKN/CMU-ECE-CS-Guide pull request #98
Opened 2023-10-24 23:03 UTC by jasonatptld

# Summary of Changes

- Please indicate the classes you are modifying:
  - 18-100
  - ...

# Checklist:

- [ ] I have added my entries to the `README.md` table of contents in the root directory as links.

Make sure that your contributions:

- [ ] Are accurate and will not mislead the reader
- [ ] Do not encourage or cause academic integrity violations
- [ ] Do not offend professors or unfairly criticize the university

2023-10-24 23:05 UTC, jasonatptld commented
I am not very experienced with Github.  I have no idea if I did this fork/pull request correctly.

2023-10-25 14:19 UTC, mikinty requested changes
This is pretty good, a few comments, and also you need to add this to the table of contents

2023-10-25 14:19 UTC, mikinty commented on electives/18865
> +-Instructor office hours are in Rwanda time.  This makes for limited access to the instructor outside of the few office hours/week. That said, the instructor does respond to WhatsApp and does try to
Add space after `-`

2023-10-25 14:19 UTC, mikinty commented on electives/18865
> +
Extra space, get rid of this

2023-10-25 14:19 UTC, mikinty commented on electives/18865
> +## Resources
You should install a markdown formatter, it will do stuff like add an extra space after headers

2023-10-25 14:19 UTC, mikinty commented on electives/18865
> +
Get rid of one of these spaces

2023-10-25 14:19 UTC, mikinty commented on electives/18865
> +# 18-865: Power Electronics for Electric Utility Systems
Please make this an `.md` (Markdown) file. Right now it has no file extension

2023-10-25 18:26 UTC, jasonatptld commented
Updated white space, created a new .md file.  I did create a link in the directory, but it may have been broken due to the non .md file.

2023-10-29 14:48 UTC, jasonatptld commented
I've become a bit lost with this process.  Is there anything else I need to do to get the 18-865 content added to the repository?

2023-10-29 15:12 UTC, mikinty commented
> I've become a bit lost with this process.  Is there anything else I need to do to get the 18-865 content added to the repository?

Yes same issues as mentioned before...you didn't modify the table of contents in this PR. You opened a new PR and I said to please put those changes in this one. You can see this PR only contains the new file, no changes to the table of contents.

2023-10-29 15:28 UTC, mikinty approved these changes
Thanks for addressing feedback!

2023-10-29 15:28 UTC, merged

2023-10-29 15:29 UTC, jasonatptld commented
OK.  I've added 18-865 to the table of contents (for the third time).  I'm not sure what happened to it the first time I added it.  Maybe I was in the wrong area of Github.  Please let me know if its all correct now.  Regards.